# Generated by Django 4.1.5 on 2023-02-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Tanks', 'Танки'), ('Healers', 'Хилы'), ('DD', 'ДД'), ('Traders', 'Торговцы'), ('GMs', 'Гилдмастеры'), ('QGs', 'Квестгиверы'), ('Blacksmiths', 'Кузнецы'), ('Leatherworkers', 'Кожевники'), ('Potionmaker', 'Зельевары'), ('SM', 'Мастера заклинаний')], default='Танки', max_length=50),
        ),
    ]
