# Generated by Django 4.1.5 on 2023-02-01 16:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_remove_post_replyers_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
