# Generated by Django 4.1.5 on 2023-02-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_alter_reply_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='accept_value',
            field=models.BooleanField(default=None),
        ),
    ]
