# Generated by Django 4.1.5 on 2023-02-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_alter_reply_accept_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='accept_value',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
